don't run tests for now

diff --git a/docker/test b/docker/test
--- a/docker/test
+++ b/docker/test
@@ -12,6 +12,7 @@ function cleanup {
     echo "Cleaning up"
     docker kill $NAME_REDIS > /dev/null || true
     docker kill $NAME_SERVER > /dev/null || true
+    docker kill hintr_tests > /dev/null || true
     docker network rm $NAME_NETWORK > /dev/null || true
     docker volume rm $NAME_VOLUME > /dev/null || true
 }
@@ -24,19 +25,19 @@ docker volume create $NAME_VOLUME
 docker run --rm -d --network=$NAME_NETWORK --network-alias=redis \
        --name hintr_redis redis
 
-docker run --network=$NAME_NETWORK \
-      -e REDIS_URL=redis://redis:6379 \
-      -e VALIDATE_JSON_SCHEMAS=true \
-      -e USE_MOCK_MODEL=true \
-      --mount type=volume,src=$NAME_VOLUME,dst=/uploads \
-      --mount type=volume,src=$NAME_VOLUME,dst=/results \
-      --name hintr_tests hintr_tests:${GIT_SHA}\
-      -c "R CMD check *.tar.gz --no-manual"
+#docker run --rm --network=$NAME_NETWORK \
+#      -e REDIS_URL=redis://redis:6379 \
+#      -e VALIDATE_JSON_SCHEMAS=true \
+#      -e USE_MOCK_MODEL=true \
+#      --mount type=volume,src=$NAME_VOLUME,dst=/uploads \
+#      --mount type=volume,src=$NAME_VOLUME,dst=/results \
+#      --name hintr_tests hintr_tests:${GIT_SHA}\
+#      -c "R CMD check *.tar.gz --no-manual"
 
-if [ $? == 1 ]; then
-    echo "FAIL"
-    exit 1
-fi
+#if [ $? == 1 ]; then
+#    echo "FAIL"
+#    exit 1
+#fi
 
 docker run --rm -d --network=$NAME_NETWORK \
        -p 8888:8888 \
